name: Scheduled health check

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  check-health:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://digital-coins-store.azurewebsites.net
